[package]
name = "montre-query"
description = "Query parser and executor for Montre corpus query engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
montre-core = { workspace = true }
montre-index = { workspace = true }
winnow = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
montre-build = { workspace = true }
